version: '3.8'

services:
  jupyterlab:
    build: ./base
    volumes:
      - ./base/code:/opt/app/src
      - $HOME/.Xauthority:/root/.Xauthority:rw
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
    network_mode: host
